# Generated by Django 4.1.2 on 2022-10-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codaluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=45, unique=True)),
                ('curso_aluno', models.CharField(max_length=45)),
                ('biografia', models.TextField(max_length=5000)),
                ('linkedin', models.URLField(max_length=100)),
                ('foto', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('CodForumItem', models.AutoField(primary_key=True, serialize=False)),
                ('DescForum', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'Forum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('codsite', models.AutoField(primary_key=True, serialize=False)),
                ('nome_site', models.CharField(max_length=100, unique=True)),
                ('home_page', models.URLField(max_length=100)),
                ('descricao', models.TextField(max_length=600)),
                ('logo', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'site',
                'managed': True,
            },
        ),
    ]
