# Generated by Django 4.0.5 on 2022-06-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome_site', models.CharField(default='AJUSTAR', max_length=100, unique=True)),
                ('home_page', models.CharField(default='AJUSTAR', max_length=100, unique=True)),
            ],
        ),
    ]
