# Generated by Django 4.0.5 on 2022-06-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devlittlegirls_app', '0002_aluno_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='site',
        ),
    ]
